export const ERRORS = {
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_ASSEMBLY: 'ITEM_NOT_ASSEMBLY',
  ASSEMBLY_COMPONENTS_REQUIRED: 'ASSEMBLY_COMPONENTS_REQUIRED',
  ASSEMBLY_COMPONENT_ITEM_NOT_FOUND: 'ASSEMBLY_COMPONENT_ITEM_NOT_FOUND',
  ASSEMBLY_COMPONENT_ITEM_NOT_INVENTORY:
    'ASSEMBLY_COMPONENT_ITEM_NOT_INVENTORY',
  ASSEMBLY_COMPONENT_ITEM_DUPLICATED:
    'ASSEMBLY_COMPONENT_ITEM_DUPLICATED',
  ASSEMBLY_COMPONENT_SELF_REFERENCE:
    'ASSEMBLY_COMPONENT_SELF_REFERENCE',
  ASSEMBLY_COMPONENT_QUANTITY_INVALID:
    'ASSEMBLY_COMPONENT_QUANTITY_INVALID',
  ASSEMBLY_QUANTITY_INVALID: 'ASSEMBLY_QUANTITY_INVALID',
  ASSEMBLY_INVENTORY_ACCOUNT_REQUIRED:
    'ASSEMBLY_INVENTORY_ACCOUNT_REQUIRED',
  ASSEMBLY_COST_ACCOUNT_REQUIRED: 'ASSEMBLY_COST_ACCOUNT_REQUIRED',
  ASSEMBLY_COMPONENTS_UNAVAILABLE: 'ASSEMBLY_COMPONENTS_UNAVAILABLE',
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
};
