export const ERRORS = {
  PAYMENT_NOT_FOUND: 'EXPENSE_PAYMENT_NOT_FOUND',
  PAYMENT_NUMBER_NOT_UNIQUE: 'EXPENSE_PAYMENT_NUMBER_NOT_UNIQUE',
  PAYMENT_ACCOUNT_NOT_FOUND: 'EXPENSE_PAYMENT_ACCOUNT_NOT_FOUND',
  PAYMENT_ACCOUNT_NOT_CURRENT_ASSET_TYPE:
    'EXPENSE_PAYMENT_ACCOUNT_NOT_CURRENT_ASSET_TYPE',
  EXPENSE_ENTRIES_IDS_NOT_FOUND: 'EXPENSE_ENTRIES_IDS_NOT_FOUND',
  PAYMENT_ENTRIES_NOT_FOUND: 'EXPENSE_PAYMENT_ENTRIES_NOT_FOUND',
  INVALID_EXPENSE_PAYMENT_AMOUNT: 'INVALID_EXPENSE_PAYMENT_AMOUNT',
  PAYMENT_VENDOR_SHOULD_NOT_MODIFY: 'PAYMENT_VENDOR_SHOULD_NOT_MODIFY',
  EXPENSES_NOT_OPENED_YET: 'EXPENSES_NOT_OPENED_YET',
  WITHDRAWAL_ACCOUNT_CURRENCY_INVALID:
    'EXPENSE_PAYMENT_WITHDRAWAL_ACCOUNT_CURRENCY_INVALID',
  EXPENSES_HAVE_DIFFERENT_PAYABLE_ACCOUNTS:
    'EXPENSES_HAVE_DIFFERENT_PAYABLE_ACCOUNTS',
  EXPENSES_HAVE_DIFFERENT_CURRENCIES: 'EXPENSES_HAVE_DIFFERENT_CURRENCIES',
};
